// packages/solid-realtime/src/useChannel.ts
import { createEffect, createSignal, onCleanup } from 'solid-js'
import { serializeKey } from '@tanstack/realtime'
import { useRealtimeClient } from './context.js'
import type { Accessor } from 'solid-js'
import type { QueryKey, SubscribeError } from '@tanstack/realtime'

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export interface UseChannelResult {
  /**
   * Stable publish function bound to `channel`.
   * Returns a `Promise<void>` that resolves when the transport dispatches the
   * message — `await` it for backpressure or optimistic UI confirmation.
   */
  publish: (data: unknown) => Promise<void>
  /**
   * Reactive accessor for the most recent subscribe error for this channel,
   * or `null` if the subscription is healthy. Resets to `null` when `channel`
   * changes. Only populated when `onMessage` is provided (subscribe-mode).
   */
  subscribeError: Accessor<SubscribeError | null>
}

// ---------------------------------------------------------------------------
// Primitive
// ---------------------------------------------------------------------------

/**
 * Convenience primitive that combines `useSubscribe` and `usePublish` for a
 * single channel — eliminating the need to repeat the channel key.
 *
 * The `onMessage` callback is **optional**. Omit it for publish-only scenarios.
 * The subscription is only established when `onMessage` is provided.
 *
 * Must be used inside `<RealtimeProvider>`.
 *
 * @example
 * // Chat room — send and receive on the same channel
 * function ChatRoom(props) {
 *   const [messages, setMessages] = createSignal<Message[]>([])
 *   const { publish } = useChannel(
 *     ['chat', { roomId: props.roomId }],
 *     (raw) => setMessages((prev) => [...prev, raw as Message]),
 *   )
 *
 *   return (
 *     <>
 *       <For each={messages()}>{(m) => <p>{m.text}</p>}</For>
 *       <button onClick={() => publish({ id: crypto.randomUUID(), text: 'Hi!' })}>
 *         Send
 *       </button>
 *     </>
 *   )
 * }
 *
 * @example
 * // Publish-only — no subscription
 * const { publish } = useChannel(['analytics', { page }])
 * await publish({ event: 'pageview' })
 */
export function useChannel(
  channel: QueryKey | string,
  onMessage?: (data: unknown) => void,
): UseChannelResult {
  const client = useRealtimeClient('useChannel')

  const serializedChannel =
    typeof channel === 'string' ? channel : serializeKey(channel)

  const [subscribeError, setSubscribeError] =
    createSignal<SubscribeError | null>(null)

  // Keep the latest callback in a plain variable so the subscription is not
  // torn down and re-established when the function reference changes.
  let latestOnMessage = onMessage

  createEffect(() => {
    setSubscribeError(null)
    latestOnMessage = onMessage

    if (!onMessage) return

    const unsubMessage = client.subscribe(serializedChannel, (data) =>
      latestOnMessage?.(data),
    )

    const unsubError = client.onSubscribeError((ch, reason, code) => {
      if (ch === serializedChannel) {
        setSubscribeError({ channel: ch, reason, code })
      }
    })

    onCleanup(() => {
      unsubMessage()
      unsubError()
    })
  })

  const publish = (data: unknown): Promise<void> =>
    client.publish(serializedChannel, data)

  return { publish, subscribeError }
}

// packages/react-realtime/src/useChannel.ts
import { use, useCallback, useEffect, useRef, useState } from 'react'
import { serializeKey } from '@tanstack/realtime'
import { RealtimeContext } from './context.js'
import type { QueryKey, SubscribeError } from '@tanstack/realtime'

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export interface UseChannelResult {
  /**
   * Stable publish function bound to `channel`.
   * Returns a `Promise<void>` that resolves when the transport dispatches the
   * message — `await` it for backpressure or optimistic UI confirmation.
   */
  publish: (data: unknown) => Promise<void>
  /**
   * The most recent subscribe error for this channel, or `null` if the
   * subscription is healthy. Resets to `null` when `channel` changes.
   * Only populated when `onMessage` is provided (subscribe-mode).
   */
  subscribeError: SubscribeError | null
}

// ---------------------------------------------------------------------------
// Hook
// ---------------------------------------------------------------------------

/**
 * Convenience hook that combines `useSubscribe` and `usePublish` for a single
 * channel — eliminating the need to repeat the channel key in two hooks.
 *
 * The `onMessage` callback is **optional**. Omit it for publish-only scenarios.
 * The subscription is only established when `onMessage` is provided.
 *
 * The callback is kept current via a ref so it always sees the latest closure
 * values without triggering a re-subscription when the function reference
 * changes between renders.
 *
 * Must be used inside `<RealtimeProvider>`.
 *
 * @example
 * // Chat room — send and receive on the same channel
 * function ChatRoom({ roomId }: { roomId: string }) {
 *   const [messages, setMessages] = useState<Message[]>([])
 *   const { publish } = useChannel(
 *     ['chat', { roomId }],
 *     (raw) => setMessages((prev) => [...prev, raw as Message]),
 *   )
 *
 *   return (
 *     <>
 *       {messages.map((m) => <p key={m.id}>{m.text}</p>)}
 *       <button onClick={() => publish({ id: crypto.randomUUID(), text: 'Hi!' })}>
 *         Send
 *       </button>
 *     </>
 *   )
 * }
 *
 * @example
 * // Publish-only — no subscription
 * const { publish } = useChannel(['analytics', { page }])
 * await publish({ event: 'pageview' })
 */
export function useChannel(
  channel: QueryKey | string,
  onMessage?: (data: unknown) => void,
): UseChannelResult {
  const client = use(RealtimeContext)
  if (!client) {
    throw new Error(
      '[realtime] useChannel must be used inside <RealtimeProvider>.',
    )
  }

  const serializedChannel =
    typeof channel === 'string' ? channel : serializeKey(channel)

  const [subscribeError, setSubscribeError] = useState<SubscribeError | null>(
    null,
  )

  // Keep the latest callback in a ref so the subscription is not torn down
  // and re-established on every render when the caller does not memoize it.
  const onMessageRef = useRef(onMessage)
  onMessageRef.current = onMessage

  useEffect(() => {
    setSubscribeError(null)

    if (!onMessageRef.current) return

    const unsubMessage = client.subscribe(serializedChannel, (data) =>
      onMessageRef.current?.(data),
    )

    const unsubError = client.onSubscribeError((ch, reason, code) => {
      if (ch === serializedChannel) {
        setSubscribeError({ channel: ch, reason, code })
      }
    })

    return () => {
      unsubMessage()
      unsubError()
    }
    // Re-subscribe only when the channel string or client instance changes.
    // Boolean(onMessage) ensures the subscription is set up/torn down when
    // onMessage transitions between provided and omitted.
  }, [client, serializedChannel, Boolean(onMessage)]) // eslint-disable-line react-hooks/exhaustive-deps

  const publish = useCallback(
    (data: unknown): Promise<void> => client.publish(serializedChannel, data),
    [client, serializedChannel],
  )

  return { publish, subscribeError }
}
